services:

  # ============================================================
  # Airflow Metadata Database
  # ============================================================
  airflow-postgres:
    image: postgres:16
    container_name: commerce_airflow_postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U airflow -d airflow"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # ============================================================
  # Airflow Database Initialization
  # ============================================================
  airflow-init:
    networks:
      - commerce-network

    build:
      context: .
      dockerfile: Dockerfile.airflow

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

      DB_HOST: postgres
      DB_PORT: 5433
      DB_NAME: commerce_lakehouse
      DB_USER: postgres
      DB_PASSWORD: postgres

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project

    command: >
      bash -c "
      airflow db migrate
      "


  # ============================================================
  # Airflow Scheduler
  # ============================================================
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: commerce_airflow_scheduler

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

      DB_HOST: postgres
      DB_PORT: 5433
      DB_NAME: commerce_lakehouse
      DB_USER: postgres
      DB_PASSWORD: postgres

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project

    command: scheduler

    networks:
      - commerce-network



  # ============================================================
  # Airflow DAG Processor
  # ============================================================
  airflow-dag-processor:

    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: commerce_airflow_dag_processor

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

      DB_HOST: postgres
      DB_PORT: 5433
      DB_NAME: commerce_lakehouse
      DB_USER: postgres
      DB_PASSWORD: postgres

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project

    command: dag-processor

    networks:
      - commerce-network


  # ============================================================
  # Airflow API Server / Web UI
  # ============================================================
  airflow-api-server:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: commerce_airflow_api_server

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

      DB_HOST: postgres
      DB_PORT: 5433
      DB_NAME: commerce_lakehouse
      DB_USER: postgres
      DB_PASSWORD: postgres

    ports:
      - "8081:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project

    command: api-server

    networks:
      - commerce-network


# ============================================================
# Docker Volumes
# ============================================================
volumes:
  airflow_postgres_data:

networks:
  commerce-network:
    external: true
    name: datalakehouse-platform_commerce-network
