[pytest]
testpaths = tests
addopts =
    --cov=src
    --cov-report=term-missing
    --cov-config=.coveragerc
    -v

markers =
    regression: Regression tests
    mock_df: Mock dataframe fixture

norecursedirs =
    logs
    airflow/logs
    .git
    .venv
    __pycache__
    build
    dist

